language: python
python:
- "2.7"

install:
  - pip install git+https://github.com/romanvm/Kodistubs.git#egg=Kodistubs

branches:
  only:
  - /.*/

jobs:
  include:
  - stage: Test
    script: python -m unittest test.test_get_url_opener